spring:
  application:
    name: java.api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java.api
    username: postgres
    password: postgre1234      
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true 
